apiVersion: v1
kind: Service
metadata:
  name: laravel-in-kubernetes-mysql
spec:
  selector:
    tier: backend
    layer: database
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      # nodePort: 31000